---
apiVersion: v1
kind: Service
metadata:
  name: fiap-diners-order-service
  namespace: fiap-diners
  labels:
    app: fiap-diners-order
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: fiap-diners-order
  type: LoadBalancer
